apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    run: api-service
spec:
  selector:
    app: api-pod
  ports:
  - port: 30808
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
